#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the compareTriplets function below.
def compareTriplets(a, b):
    score_a = score_b = 0

    # loop over each element and compare with corresponding element in other array
    for i, elem in enumerate(a):
        if elem > b[i]:
            score_a +=1
        elif elem == b[i]:
            pass
        elif elem < b[i]:
            score_b +=1
    return '{}{}'.format(score_a, score_b)
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    a = list(map(int, input().rstrip().split()))

    b = list(map(int, input().rstrip().split()))

    result = compareTriplets(a, b)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')
    fptr.close()
    
